### ISSUE TITLE
Invalid dictionary iteration example in docs

### ISSUE THREAD

**Issue by ivanteresh** [stencilproject/Stencil#208]
Hello!
In my application i use dictionary iteration, as described on the [official docs page](https://stencil.fuller.li/en/latest/builtins.html#built-in-tags):

But, template rendering fails in `for key, value in something` statement.
Than I dive into code of your library and see, that key value pair expects to be written without space after comma, like `for key,value in something`. So i fixed, and it worked.

Please, actualize your documentation, it will help other people to enjoy dict iteration in your library :)

**Comment by kylef** [comment]
@ivanteresh which version of Stencil are you using?

**Comment by ivanteresh** [comment]
@kylef latest, 0.11.0

**Comment by ilyapuchka** [comment]
This should be fixed with #178

**Comment by ivanteresh** [comment]
Ok, thx

**Comment by djbe** [comment]
Closing this as the PR has been merged.
