### ISSUE TITLE
Dependencies inconsistencies between CocoaPods and SPM

### ISSUE THREAD

**Issue by AliSoftware** [stencilproject/Stencil#211]
Stencil 0.11.0 currently declare the following dependencies:

* in its podspec, only declares one dependency to `PathKit ~> 0.8.0`
* in its Package.swift, declares two dependencies, one to `PathKit 0.9` and one to `Spectre 0.8`

Not sure why there's an inconsistency in the `PathKit` versions between the two, and why SPM would need a dependency to `Spectre` while CocoaPods wouldn't

**Comment by ilyapuchka** [comment]
Stencil uses SPM to build and test, so it only needs test dependencies in Package manifest. PathKit versions should match indeed but I guess `~> 0.8.0` will also match 0.9 version when installed via CocoaPods

**Comment by AliSoftware** [comment]
By definition, `~> 0.8.0` matches any `0.8.x` where `x > 0`. But doesn't match `0.9`. So no, CocoaPods won't fetch PathKit 0.9 with that spec definition
