### ISSUE TITLE
Editor and IDE support

### ISSUE THREAD

**Issue by svanimpe** [stencilproject/Stencil#222]
I think the success of a project like Stencil depends in part on its editor and IDE support. I started out using Stencil with a Django plugin (to get some syntax highlighting at least), but found that less than ideal, which is why I built something specifically for Stencil. Earlier this year I wrote a TextMate bundle (https://github.com/svanimpe/stencil.tmbundle) and used that to build a VS Code extension (https://github.com/svanimpe/vscode-stencil). The latter has proven quite popular, with over 500 installs. 

Unfortunately, I don't have the time to follow the repository closely and read every single commit to check if a change requires an update to the grammar. If possible, I would like to donate my work to the Stencil project.

Are you interested in this?

**Comment by AliSoftware** [comment]
That's awesome!

I think that works be 👌 to have those located in the stencilproject org to have those considered "official". We'd obviously give you full push access to it I'd we migrate then here.

Tbh I'm not sure we'll have more time and bandwidth  than you to maintain them, but at least if we host them here and link to them in the main repo and wiki and docs etc, hopefully it will allow more contributors to help us maintain those at least 😉

**Comment by svanimpe** [comment]
How shall we proceed with this? It may be easiest the keep the repos separate and simply transfer ownership to stencilproject (instead of merging everything into one repo)?

**Comment by AliSoftware** [comment]
Yeah transferring ownership is the right move 👍

**Comment by svanimpe** [comment]
It seems I need permission to do that. Can you add me?

**Comment by AliSoftware** [comment]
Sure! Just did it 👍

**Comment by svanimpe** [comment]
The projects have been transferred. I'll go through the READMEs tomorrow to see what needs updating. If you spot anything, feel free to let me know.

W.r.t. the VS Code Marketplace: I'll update the links, but it may be easier (for continuity) to keep the extension under my account? I'll just tag and push a new version when we have one.

**Comment by svanimpe** [comment]
The READMEs for both repositories have been updated and a new version of the extension has been pushed (with updated metadata).

**Comment by AliSoftware** [comment]
I think it would be nice to add a mention of those in the docs in this Stencil repo too, to let people know it exists 👍

**Comment by ilyapuchka** [comment]
@svanimpe with the new organization will it make sense to move those plugins under StencilProject namespace? This might help to keep them up to date.

**Comment by yonaskolb** [comment]
@ilyapuchka I believe that’s what happened 
https://github.com/stencilproject/vscode-stencil

**Comment by ilyapuchka** [comment]
Oh nice, didn't notice when that has happened. I suppose we can close this then

**Comment by ilyapuchka** [comment]
And I didn't read the discussion =)
