### ISSUE TITLE
Release 0.13.0 (or 0.12.2)

### ISSUE THREAD

**Issue by djbe** [stencilproject/Stencil#250]
0.12.1 contains the error improvements, but also the massive slowdown from it. It was quickly fixed after that, but current Stencil users are still stuck with those slowdowns.

- We can release a bugfix version 0.12.2 with only #230, although it'd be a little bit harder because there have been a bunch of commits since then. We'd probably have to create a 0.12.x branch, update the package/podspec there, and create a tag.
- Or we can release 0.13.0, which drops Swift 3 support, but brings a bunch of fixes for Xcode 10 users (we may want to also merge #226 for performance).

Thoughts? My vote goes to release 0.13.

**Comment by AliSoftware** [comment]
I'd say we go 0.13

Since we can now build Swift 4 since a while it's not like it was brand newly released, shouldn't be a blocker (and we also have the excuse that we're still on 0.x so can be less strict about that 😅😜)

**Comment by yonaskolb** [comment]
0.13 👍
