### ISSUE TITLE
Boolean expression: parenthesis need to be surrounded by spaces

### ISSUE THREAD

**Issue by djbe** [stencilproject/Stencil#253]
Refs #165.

This is either a bug in the implementation, or in the documentation. The docs say:
`{% if (one or two) and three %}`
But that won't work. It'll throw a "dangling token" error. What does work is:
`{% if ( one or two ) and three %}`

The reason is that the current implementation is just built on top of the components array received from the token parser, which separates by spaces. @ilyapuchka thoughts?

**Comment by ilyapuchka** [comment]
it shouldn't be like that, I need to look into that later
