### ISSUE TITLE
How do I recurse

### ISSUE THREAD

**Issue by feixue299** [stencilproject/Stencil#260]

**Comment by ilyapuchka** [comment]
@feixue299 can you elaborate on that?

**Comment by djbe** [comment]
A few of our templates in [SwiftGen](https://github.com/SwiftGen/SwiftGen) recurse through dictionaries. We use a combination of `macro` & `call` tags to achieve this, which are implemented in [StencilSwiftKit](https://github.com/SwiftGen/StencilSwiftKit), an add-on for Stencil.
