### ISSUE TITLE
Not complete support with Mustache

### ISSUE THREAD

**Issue by rkbansal** [stencilproject/Stencil#271]
I wonder if there is a way in the stencil to support the exact syntax of the mustache.
How can someone just parse the if and endif condition in the mustache?
Right conditions in stencil are like this,
{% if activeFilesCount %}
    {{activeFilesCount}}
{% endif %}

but how can I use the template in mustache as it has different syntax than this?

**Comment by ilyapuchka** [comment]
Stencil is not implementation of Mustache, it's a templating DSL on its own. If you need implementation of Mustache checkout https://mustache.github.io
