### ISSUE TITLE
Website is inaccessible because of Cloudfare error. 

### ISSUE THREAD

**Issue by kennycarruthers** [stencilproject/Stencil#283]
Attempting to access https://stencil.fuller.li to view the documentation is currently broken. A Cloudfare error page is shown instead. 

<img width="947" alt="Screen Shot 2019-08-13 at 9 17 45 pm" src="https://user-images.githubusercontent.com/15756/62949112-cf1bc000-be0f-11e9-8991-36b35c3093b6.png">

**Comment by michaelosity** [comment]
Same issue here. Seems like a lot of people have this problem. https://twitter.com/stefanprodan/status/834872543790174209 may help? Not sure if there is anything we can do on the Cloudflare side.

**Comment by hamsternik** [comment]
Same trouble nowadays. @kylef @ilyapuchka @djbe you could resolve this issue, i guess.

**Comment by kylef** [comment]
Same problem as https://github.com/kylef/swiftenv/issues/162#issuecomment-518191162. Issued the same fix, it may take a little bit of time due to the nature of DNS TTL.

**Comment by hamsternik** [comment]
Thanks a lot, @kylef 🙏 

Now it's works!
