### ISSUE TITLE
SPM: endless fetching https://github.com/kylef/Stencil.git

### ISSUE THREAD

**Issue by anothercoder42** [stencilproject/Stencil#284]
I'm trying to install Kitura and Stencil from the RayWenderlich Videos project .

This is the file from the Package.swift: .package(url: "https://github.com/IBM-Swift/Kitura-StencilTemplateEngine.git", .upToNextMinor(from: "1.9.1"))

After doing 'swift build', the process gets stuck at 

Fetching https://github.com/kylef/Stencil.git

Using Xcode 11 + it's CLI

Any ideas what might be wrong or where I might look to get forward?

**Comment by barrymcbride** [comment]
Having this same issue

**Comment by djbe** [comment]
Sounds like an SPM issue.

Just guessing, but maybe change the URL to `https://github.com/stencilproject/Stencil.git` instead of `https://github.com/kylef/Stencil.git`? (the project was renamed quite a while ago).

**Comment by djbe** [comment]
AFAIK this was because the wrong URL, just use the new one and it'll work fine.
