### ISSUE TITLE
[Question] Releasing a new version for 'Swift 5' ?

### ISSUE THREAD

**Issue by lennartstolz** [stencilproject/Stencil#285]
In #268 the Swift 5 support was introduced but no new version was released since then.

Is there any plan to do so? If so I'm happy to help.

Best,
Lennart

(Backing: https://github.com/stencilproject/Stencil/pull/268#issuecomment-495271361)

**Comment by lennartstolz** [comment]
@djbe / @kylef any news about a "Swift 5" release? 😊

**Comment by AliSoftware** [comment]
0.14.0 is now out!
