### ISSUE TITLE
New release for PathKit version bump

### ISSUE THREAD

**Issue by CraigSiemens** [stencilproject/Stencil#293]
In master, it looks like path kit has been updated to version 1.0. Currently running into an issue where there is a version conflict caused by two dependencies requiring different versions of path kit. In my case it's:

- Apollo -> Stencil -> PathKit 0.9
- XcodeGen -> PathKit 1.0

The current work around is to use and older version of XcodeGen, but it's about a year behind and not the best solution.

Could there be a new release?

**Comment by lennartstolz** [comment]
+1

https://github.com/stencilproject/Stencil/issues/285

**Comment by jasdeepsaini** [comment]
Any plans to do a new release?

**Comment by fortmarek** [comment]
First of all, I'd like to thank for all the hard work that has been done on this project, it's really been great!

I realize that maintaining opensource projects takes time and it's something most of us are doing for free - but this is becoming a real issue for our project [tuist](https://github.com/tuist/tuist) as we'll need to spin up our own fork going forward which is something we'd like to avoid. Is there anyway we can give a helping hand if none of the maintainers have the time to create a new release? 🙂 Maybe if @djbe would have some time to respond? 🙏

**Comment by AliSoftware** [comment]
I'll try to take a look at this in the upcoming weeks; I'm currently in the middle of an long job interview process so no guarantee I'll have a lot of time to concentrate on that soon but it should totally be doable.

**Comment by AliSoftware** [comment]
Btw if anyone from tuist wants to become a co-maintainer of Stencil to help us on that, don't hesitate to ping us
/wink @fortmarek @pepibumur 😉

**Comment by AliSoftware** [comment]
0.14.0 is now out! https://github.com/stencilproject/Stencil/releases/tag/0.14.0
