### ISSUE TITLE
@Prop with type of an interface ends up in an typescript error

### ISSUE THREAD

**Issue by LutzStrobel** [stencilproject/Stencil#302]
I have an interface like that:
export default interface PostRecord{
 ...
}

and a component like this:

export class Container implements ComponentInterface {

@Prop record: PostRecord;

...
}
with a correct import of PostRecord.
Then the typescript compiler complains:
 [ ERROR ]  TypeScript: ./src/components.d.ts:29:19
[0]            Cannot find name 'PostRecord'.
[0]
[0]      L28:      "active": boolean;
[0]      L29:      "record": PostRecord;
[0]      L30:  }

Is it possible to use interface types as property types or what is wrong with the picture?
Thank you for your help.
Lutz

**Comment by yonaskolb** [comment]
Hi @LutzStrobel. I think you posted to the wrong repo?

**Comment by LutzStrobel** [comment]
Really, the wrong repo.
Thanx
