### ISSUE TITLE
Release a new version that supports Xcode 13

### ISSUE THREAD

**Issue by subdan** [stencilproject/Stencil#318]
Hello, @svanimpe.

Please, release a new version of Stencil. Changes in the master branch adds support for Xcode 13. I need these changes for my CLI utility [FigmaExport](https://github.com/RedMadRobot/figma-export).

Thanks.

**Comment by svanimpe** [comment]
Hi @subdan 
I'm not actually a maintainer/contributer for this project :) But I assume someone who is wil reply to this issue?

**Comment by subdan** [comment]
Oops. I've found you on this page as an author https://github.com/stencilproject

**Comment by subdan** [comment]
@djbe, could you please release a new version?

**Comment by subdan** [comment]
Thanks!
